"""fulltitle field to Download model

Revision ID: bace57d7e093
Revises: dc5c729a0eaa
Create Date: 2025-01-10 20:06:23.595028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bace57d7e093'
down_revision: Union[str, None] = 'dc5c729a0eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('fulltitle', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'fulltitle')
    # ### end Alembic commands ###
