"""Add youtube_id, title, uploader, channel, duration, label, copyright, origin_url, live_status, extractor and categories fields

Revision ID: dc5c729a0eaa
Revises: abe28b561564
Create Date: 2025-01-10 18:29:51.597496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5c729a0eaa'
down_revision: Union[str, None] = 'abe28b561564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('youtube_id', sa.String(length=20), nullable=False))
    op.add_column('downloads', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('downloads', sa.Column('uploader', sa.String(length=50), nullable=False))
    op.add_column('downloads', sa.Column('channel', sa.String(length=50), nullable=False))
    op.add_column('downloads', sa.Column('duration', sa.String(length=5), nullable=False))
    op.add_column('downloads', sa.Column('label', sa.String(length=25), nullable=False))
    op.add_column('downloads', sa.Column('copyright', sa.String(length=25), nullable=False))
    op.add_column('downloads', sa.Column('origin_url', sa.String(length=255), nullable=False))
    op.add_column('downloads', sa.Column('live_status', sa.String(length=10), nullable=False))
    op.add_column('downloads', sa.Column('extractor', sa.String(length=25), nullable=False))
    op.add_column('downloads', sa.Column('categories', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'categories')
    op.drop_column('downloads', 'extractor')
    op.drop_column('downloads', 'live_status')
    op.drop_column('downloads', 'origin_url')
    op.drop_column('downloads', 'copyright')
    op.drop_column('downloads', 'label')
    op.drop_column('downloads', 'duration')
    op.drop_column('downloads', 'channel')
    op.drop_column('downloads', 'uploader')
    op.drop_column('downloads', 'title')
    op.drop_column('downloads', 'youtube_id')
    # ### end Alembic commands ###
